title: "S. P. Sarkar"
email: "your-email@example.com"
description: >-
  Personal website and blog of S. P. Sarkar.
baseurl: ""
url: "https://spsarkar.github.io"
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: "default"
locale: "en-US"
# Add more configuration as needed
