source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
# gem "minimal-mistakes-jekyll"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "jemoji"
gem "jekyll-include-cache"
